URL: http://ghcr-web.dev  # required
GITHUB_CLIENT_ID: ""      # required
GITHUB_CLIENT_SECRET: ""  # required
RAVEN_DSN: ""             # optional
HIPCHAT_TOKEN: ""         # optional
HIPCHAT_ROOM: ""          # optional
